# Cleans up unnecessary metadata XML files generated by arcpy.CopyRaster function.
# Runs from the root directory (folder of folders of folders)

import os
import sys

if __name__ == "__main__":
    if len(sys.argv) == 2:
        root_dir = sys.argv[1]
    else:
        print('Usage: python3 cleanup.py "C:/Users/.../Root Folder"')
        exit(1)

    for folder in os.listdir(root_dir):
        for subfolder in os.listdir(f'{root_dir}/{folder}'):
            for file in os.listdir(f'{root_dir}/{folder}/{subfolder}'):
                if file.endswith('.mrf.xml'):
                    print(f'Removing {root_dir}/{folder}/{subfolder}/{file}')
                    os.remove(f'{root_dir}/{folder}/{subfolder}/{file}')

    print('Finished cleaning up metadata files')
