# Converts all GeoTIFF raster datasets existing in a root directory to MRFs

import os
import sys
import arcpy


def convert_raster(input_dir, output_dir):
    """
    Recursive function that converts all raster datasets under an input directory
    into an output folder
    """
    pixel_t = '8_BIT_UNSIGNED'
    nodata_val = 255  # max unsigned 8-bit val

    for file in os.listdir(input_dir):
        if file.endswith('.tif'):
            if 'narea_areakm2' in file:
                continue

            output_rast = file.replace('.tif', '.mrf')

            if 'ga50' in file:
                output_rast = f'{os.path.basename(input_dir)}_ga50.mrf'
            elif '_median' in file:
                output_rast = f'{os.path.basename(input_dir)}_spdist_thrsld_median.mrf'

            print('Converting', os.path.join(input_dir, file))
            try:
                for cls in ['ersIn', 'ersIn_ecos', 'ersEx', 'ersEx_ecos']:
                    if cls in file:
                        pixel_t = '32_BIT_UNSIGNED'
                        nodata_val = 4294967295  # max unsigned 32-bit val
                        break

                arcpy.CopyRaster_management(
                    in_raster=os.path.join(input_dir, file),
                    out_rasterdataset=os.path.join(output_dir, output_rast),
                    background_value=nodata_val,
                    nodata_value=nodata_val,
                    pixel_type=pixel_t,
                    format='MRF',
                    transform='NONE'
                )
            except KeyboardInterrupt:
                exit()
            except:
                pass
        elif os.path.isdir(os.path.join(input_dir, file)):
            try:
                os.mkdir(os.path.join(output_dir, file))
            except FileExistsError:
                pass

            convert_raster(os.path.join(input_dir, file),
                           os.path.join(output_dir, file))


def checkup(input_dir, output_dir, no_match):
    """
    Double checks that for every TIF there is a corresponding MRF in all the root
    directory's subdirectories
    """
    for file in os.listdir(input_dir):
        if '__thrsld' in file or 'narea_areakm2' in file:
            continue
        elif 'ga50' in file:
            file = file.replace('ga50', f'{os.path.basename(input_dir)}_ga50')
        elif '_median' in file:
            file = file.replace('spdist_thrsld_median',
                                f'{os.path.basename(input_dir)}_spdist_thrsld_median')

        if file.endswith('.tif'):
            if file.replace('.tif', '.mrf.aux.xml') not in os.listdir(output_dir):
                no_match.append(os.path.join(input_dir, file))
        elif os.path.isdir(os.path.join(input_dir, file)):
            checkup(os.path.join(input_dir, file),
                    os.path.join(output_dir, file), no_match)


def cleanup(input_dir):
    """
    Cleans up unnecessary metadata XML files generated by arcpy.CopyRaster function
    Runs from the root directory
    """
    for file in os.listdir(input_dir):
        if file.endswith('.mrf.xml'):
            os.remove(os.path.join(input_dir, file))
        elif os.path.isdir(os.path.join(input_dir, file)):
            cleanup(os.path.join(input_dir, file))


def raise_os_error():
    raise OSError(
        'Usage: python3 convert_rasters.py [input folder] [output folder]')


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise_os_error()

    input_dir = sys.argv[1]
    output_dir = sys.argv[2]

    if not os.path.isdir(input_dir) or not os.path.isdir(output_dir):
        raise_os_error()

    arcpy.env.compression = 'LERC 0'
    arcpy.env.outputCoordinateSystem = arcpy.SpatialReference(
        'WGS 1984 UTM Zone 14N')
    arcpy.env.rasterStatistics = 'STATISTICS 1 1'
    arcpy.env.overwriteOutput = False

    convert_raster(input_dir, output_dir)
    print('Finished converting')

    no_match = []
    checkup(input_dir, output_dir, no_match)

    if no_match:
        print('The following rasters do not have a match:')
        for raster in no_match:
            print(raster)
    else:
        print('All TIFs have a matching MRF')

    cleanup(output_dir)
    print('Finished cleaning up metadata files')
