# Cleans up unnecessary metadata XML files generated by arcpy.CopyRaster function.
# Runs from the root directory

import os
import sys

def cleanup(input_dir):
    for file in os.listdir(input_dir):
        if file.endswith('.mrf.xml'):
            os.remove(f'{input_dir}/{file}')
        elif os.path.isdir(f'{input_dir}/{file}'):
            cleanup(f'{input_dir}/{file}')

if __name__ == "__main__":
    if len(sys.argv) == 2:
        root_dir = sys.argv[1]
    else:
        print('Usage: python3 cleanup.py [root folder]')
        exit()

    cleanup(root_dir)
    print('Finished cleaning up metadata files')
